apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-roh8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-roh8
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-roh8
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-roh8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-roh8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-sorf-tenant/appstudio/dc-metro-map-roh8@sha256:affc919fe5d4ee7ceaf1b98695972e505923ba5d8061bd95a9fab1eed031d20e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
